///////////////////////////////////////
// Import Dependencies
///////////////////////////////////////
const mongoose = require('./connection')
const Book = require('./book')


///////////////////////////////////////
// Seed Script code
///////////////////////////////////////
// first we need our connection saved to a variable for easy reference
const db = mongoose.connection

db.on('open', () => {
    // bring in the array of starter books
    const startBooks = [
        { title: "The Weight of Blood", subtitle: " ", cover: "../images/weightofblood.jpeg", authors: "Tiffany D. Jackson", pageCount: "406", genre: "Fiction, Horror, Thriller, YA" , description: `When Springville residents—at least the ones still alive—are questioned about what happened on prom night, they all have the same explanation . . . Maddy did it. \n
        An outcast at her small-town Georgia high school, Madison Washington has always been a teasing target for bullies. And she's dealt with it because she has more pressing problems to manage. Until the morning a surprise rainstorm reveals her most closely kept secret: Maddy is biracial. She has been passing for white her entire life at the behest of her fanatical white father, Thomas Washington.\n
        After a viral bullying video pulls back the curtain on Springville High's racist roots, student leaders come up with a plan to change their image: host the school's first integrated prom as a show of unity. The popular white class president convinces her Black superstar quarterback boyfriend to ask Maddy to be his date, leaving Maddy wondering if it's possible to have a normal life. \n But some of her classmates aren't done with her just yet. And what they don't know is that Maddy still has another secret . . . one that will cost them all their lives.`, ibsn: "9780063029149" },
        { title: "On Earth We're Briefly Gorgeous", subtitle: " ", cover: "../images/onearthgorgeous.jpeg", authors: "Ocean Vuong", pageCount: "246", genre: "Fiction, Contemporary, LGBTQIA+, Literary", description: `Poet Ocean Vuong's debut novel is a shattering portrait of a family, a first love, and the redemptive power of storytelling. \n
        On Earth We're Briefly Gorgeous is a letter from a son to a mother who cannot read. Written when the speaker, Little Dog, is in his late twenties, the letter unearths a family's history that began before he was born -- a history whose epicenter is rooted in Vietnam -- and serves as a doorway into parts of his life his mother has never known, all of it leading to an unforgettable revelation. At once a witness to the fraught yet undeniable love between a single mother and her son, it is also a brutally honest exploration of race, class, and masculinity. Asking questions central to our American moment, immersed as we are in addiction, violence, and trauma, but undergirded by compassion and tenderness, On Earth We're Briefly Gorgeous is as much about the power of telling one's own story as it is about the obliterating silence of not being heard. \n
        With stunning urgency and grace, Ocean Vuong writes of people caught between disparate worlds, and asks how we heal and rescue one another without forsaking who we are. The question of how to survive, and how to make of it a kind of joy, powers the most important debut novel of many years.`, ibsn: "9780525562023"},
        { title: "The Hunger Games", subtitle: "The Hunger Games, #1", cover: "../images/hungergames.jpeg", authors: "Suzanne Collins", pageCount: "374", genre: "Fiction, Dystopian, Science Fiction, YA", description: `In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.
        Katniss is a 16-year-old girl living with her mother and younger sister in the poorest district of Panem, the remains of what used to be the United States. Long ago the districts waged war on the Capitol and were defeated. As part of the surrender terms, each district agreed to send one boy and one girl to appear in an annual televised event called "The Hunger Games." The terrain, rules, and level of audience participation may change but one thing is constant: kill or be killed. When Kat's sister is chosen by lottery, Kat steps up to go in her place. Without really meaning to, Katniss becomes a contender. But if she is to win, she will have to start making choices that weigh survival against humanity and life against love.`, ibsn: "9780439023481"},
        { title: "Catching Fire", subtitle: "The Hunger Games, #2", cover: "../images/catchingfire.jpeg", authors: "Suzanne Collins", pageCount: "391", genre: "Fiction, Dystopian, Science-Fiction, YA", description: `Against all odds, Katniss Everdeen has won the annual Hunger Games with fellow district tribute Peeta Mellark. But it was a victory won by defiance of the Capitol and their harsh rules. Katniss and Peeta should be happy. After all, they have just won for themselves and their families a life of safety and plenty. But there are rumors of rebellion among the subjects, and Katniss and Peeta, to their horror, are the faces of that rebellion. The Capitol is angry. The Capitol wants revenge.`, ibsn: "9780439023498"},
        { title: "Mockingjay", subtitle: "The Hunger Games, #3", cover: "../images/mockingjay.jpeg", authors: "Suzanne Collins", pageCount: "390", genre: "Fiction, Dystopian, Science Fiction, YA", description: `Against all odds, Katniss Everdeen has survived the Hunger Games twice. But now that she's made it out of the bloody arena alive, she's still not safe. The Capitol is angry. The Capitol wants revenge. Who do they think should pay for the unrest? Katniss. And what's worse, President Snow has made it clear that no one else is safe either. Not Katniss's family, not her friends, not the people of District 12.
        Powerful and haunting, this thrilling final installment of Suzanne Collins's groundbreaking The Hunger Games trilogy promises to be one of the most talked about books of the year.`, ibsn: "9780439023511"},
        { title: "The Ballad of Songbirds and Snakes", subtitle: "The Hunger Games #0", cover: "../images/songbirdsnake.jpeg", authors: "Suzanne Collins", pageCount: "517", genre: "Fiction, Dystopian, YA", description: `It is the morning of the reaping that will kick off the tenth annual Hunger Games. In the Capitol, eighteen-year-old Coriolanus Snow is preparing for his one shot at glory as a mentor in the Games. The once-mighty house of Snow has fallen on hard times, its fate hanging on the slender chance that Coriolanus will be able to outcharm, outwit, and outmaneuver his fellow students to mentor the winning tribute.
        The odds are against him. He's been given the humiliating assignment of mentoring the female tribute from District 12, the lowest of the low. Their fates are now completely intertwined -- every choice Coriolanus makes could lead to favor or failure, triumph or ruin. Inside the arena, it will be a fight to the death. Outside the arena, Coriolanus starts to feel for his doomed tribute... and must weigh his need to follow the rules against his desire to survive no matter what it takes.`, ibsn: "9781338635171"},
        { title: "White: Poems", subtitle: "", cover: "../images/white.jpeg", authors: "Trevor Ketner", pageCount: "88", genre: "Poetry, LGBTQIA+", description: `[WHITE] is a book born from obsession. This debut collection of poetry from Trevor Ketner follows two paths of obsession, laying them over one another to tease out a critique of whiteness in the arts that reflects on how we think of whiteness in America. Throughout, Ketner curates a landscape that is part [auto] biography and part political synthesis.
        Ketner's work takes inspiration from seeing a retrospective of Rauschenberg's work at the Museum of Modern Art (MoMA) seven times and from teaching themselves to read tarot in two weeks. [WHITE] is a kind of combine or collage of two projects that speak to and against each other and, in their juxtaposition, become an entirely different third thing. As we follow the life of Rauschenberg, so too do we follow the journey of the fool through the major arcana of the tarot moving forward into understanding. Here is an examination of queer bodies, Rauschenberg traveling toward, through, and away from infamous lovers in pursuit of art and selfhood, eventually finding himself in "the January water / of a lake nearby / called Eden." Meanwhile, Ketner exposes the insidiousness of whiteness and its inescapable role in American history and art.`, ibsn: "9780820360393"},
        { title: "Harry Potter and the Sorcerer's Stone", subtitle: "Harry Potter #1", cover: "../images/sorcerersstone.jpeg", authors: "J.K. Rowling with Mary Grandpré (Illustrator)", pageCount: "309", genre: "Fiction, Fantasy, Middle Grade", description: `Harry Potter has never been the star of a Quidditch team, scoring points while riding a broom far above the ground. He knows no spells, has never helped to hatch a dragon, and has never worn a cloak of invisibility.
        All he knows is a miserable life with the Dursleys, his horrible aunt and uncle, and their abominable son, Dudley - a great big swollen spoiled bully. Harry's room is a tiny closet at the foot of the stairs, and he hasn't had a birthday party in eleven years.
        But all that is about to change when a mysterious letter arrives by owl messenger: a letter with an invitation to an incredible place that Harry - and anyone who reads about him - will find unforgettable.
        For it's there that he finds not only friends, aerial sports, and magic in everything from classes to meals, but a great destiny that's been waiting for him... if Harry can survive the encounter.`, ibsn: "9780590353403"},
        { title: "Harry Potter and the Chamber of Secrets", subtitle: "Harry Potter #2", cover: "../images/chamberofsecrets.jpeg", authors: "J.K. Rowling with Mary GrandPré (Illustrator)", pageCount: "352", genre: "Fiction, Fantasy, Middle Grade", description: `The summer after his first year at Hogwarts is worse than ever for Harry Potter. The Dursleys of Privet Drive are more horrible to him than ever before. And just when he thinks the endless summer vacation is over, a creature named Dobby the house-elf shows up issuing a grave warning to Harry not to go back to school or disaster will happen Of course, Harry has to go back- and he does so in grand style, in a flying-car magicked by his friends Ron and Percy Weasley. But getting back to Hogwarts isn't the cure Harry expects it to be. Almost immediately a student is found turned to stone, and then another. And somehow Harry stands accused. Could Harry Potter be the long-feared heir of Slytherin?
        Harry and friends Hermione and Ron are stretched to their limits in a desperate fight against Draco Malfoy and his gang, the hideously stuck-up new professor Gilderoy Lockheart, the malevolent owner of the diary of Tom Riddle, giant spiders, and perhaps even...Hagrid.`, ibsn: "9780439064866"},
        { title: "Harry Potter and the Prisoner of Azkaban", subtitle: "Harry Potter #3", cover: "../images/prisonerofazkaban.jpeg", authors: "J.K. Rowling with Mary GrandPré (Illustrator)", pageCount: "435", genre: "Fiction, Fantasy, Middle Grade", description: `For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.
        Now he has escaped, leaving only two clues as to where he might be headed: Harry Potter's defeat of You-Know-Who was Black's downfall as well. And the Azkaban guards heard Black muttering in his sleep, He's at Hogwarts . . . he's at Hogwarts.
        Harry Potter isn't safe, not even within the walls of his magical school, surrounded by his friends. Because on top of it all, there may well be a traitor in their midst.`, ibsn: "978043913635"},
        { title: "Harry Potter and the Goblet of Fire", subtitle: "Harry Potter #4", cover: "../images/gobletoffire.jpeg", authors: "J.K. Rowling with Mary GrandPré (Illustrator)", pageCount: "752", genre: "Fiction, Fantasy, Middle Grade, Young Adult", description: `It's the pivotal fourth novel in the seven-part saga of a young wizard's coming of age. The thickest. The juiciest yet. Harry Potter turns fourteen. But will all his friends? Rumors have persisted that one of the characters may not see the conclusion of this novel, something the author has refused either to confirm or deny. But we who love Ron, Hermione, Hagrid...even pitiful Neville Longbottom...wait anxiously to see if they will make it through safely. No one's fate is certain when Volde -- excuse me -- He-Who-Must-Not-Be-Named is part of the picture.
        What is certain is that a novel of excruciating suspense awaits, leavened by J. K. Rowling's inimitable sense of humor and the burgeoning details of her magical world. Whether it's taking a front-row seat at the International Quidditch World Cup, or meeting the new Defense-Against-the-Dark-Arts teacher, or finding out if Harry really does start a romance with Cho Chang, fans of the history-making boy-wizard will find their thirst for Hogwarts adventure slaked deliciously...at least for a little while`, ibsn: "9780439139595"},
        { title: "Harry Potter and the Order of the Phoenix", subtitle: "Harry Potter #5", cover: "../images/orderofthepheonix.jpeg", authors: "J.K. Rowling with Mary GrandPré (Illustrator)", pageCount: "768 ", genre: "Fiction, Fantasy, Young Adult", description: `In his fifth year at Hogwart's, Harry faces challenges at every turn, from the dark threat of He-Who-Must-Not-Be-Named and the unreliability of the government of the magical world to the rise of Ron Weasley as the keeper of the Gryffindor Quidditch Team. Along the way he learns about the strength of his friends, the fierceness of his enemies, and the meaning of sacrifice.`, ibsn: "9780747569374"},
        { title: "Harry Potter and the Half-Blood Prince", subtitle: "Harry Potter #6", cover: "../images/halfbloodprince.jpeg", authors: "J.K. Rowling with Mary GrandPré (Illustrator)", pageCount: "652", genre: "Fiction, Fantasy, Young Adult", description: ` The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses. And yet...
        As in all wars, life goes on. Sixth-year students learn to Apparate - and lose a few eyebrows in the process. The Weasley twins expand their business. Teenagers flirt and fight and fall in love. Classes are never straightforward, though Harry receives some extraordinary help from the mysterious Half-Blood Prince.
        So it's the home front that takes center stage in the multilayered sixth installment of the story of Harry Potter. Here at Hogwarts, Harry will search for the full and complex story of the boy who became Lord Voldemort - and thereby find what may be his only vulnerability.`, ibsn: "9780439784542"},
        { title: "Harry Potter and the Deathly Hallows", subtitle: "Harry Potter #7", cover: "../images/deathlyhallows.jpeg", authors: "J.K. Rowling with Mary GrandPré (Illustrator)", pageCount: "759 ", genre: "Fiction, Fantasy, Young Adult", description: `It all comes down to this - a final faceoff between good and evil. You plan to pull out all the stops, but every time you solve one mystery, three more evolve. Do you stay the course you started, despite your lack of progress? Do you detour and follow a new lead that may not help? Do you listen to your instincts, or your friends?
        Lord Voldemort is preparing for battle and so must Harry. With Ron and Hermione at his side, he's trying to hunt down Voldemort's Horcruxes, escape danger at every turn, and find a way to defeat evil once and for all. How does it all end?`, ibsn: "9780545010221"},
        { title: "The One", subtitle: "", cover: "../images/theone.jpeg", authors: "John Marrs", pageCount: "291", genre: "Fiction, Romance, Science Fiction, Thriller", description: `A simple DNA test is all it takes. Just a quick mouth swab and soon you'll be matched with your perfect partner—the one you're genetically made for.
        That's the promise made by Match Your DNA. A decade ago, the company announced that they had found the gene that pairs each of us with our soul mate. Since then, millions of people around the world have been matched. But the discovery has its downsides: test results have led to the breakup of countless relationships and upended the traditional ideas of dating, romance and love.
        Now five very different people have received the notification that they've been “Matched.” They're each about to meet their one true love. But “happily ever after” isn't guaranteed for everyone. Because even soul mates have secrets. And some are more shocking than others….`, ibsn: "9781488084874"},
        { title: "Pride and Prejudice", subtitle: "", cover: "../images/prideandprejudice.jpeg", authors: "Jane Austen", pageCount: "416", genre: "Fiction, Classics, Literary, Romance", description: `Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work "her own darling child" and its vivacious heroine, Elizabeth Bennet, "as delightful a creature as ever appeared in print." The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen's radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of Regency England. `, ibsn: "9780143123163"},
        { title: "Legends & Lattes", subtitle: "", cover: "../images/legendsandlattes.jpeg", authors: "Travis Baldree", pageCount: "305", genre: "Fiction, Fantasy, LGBTQIA+", description: `Worn out after decades of packing steel and raising hell, Viv the orc barbarian cashes out of the warrior's life with one final score. A forgotten legend, a fabled artifact, and an unreasonable amount of hope lead her to the streets of Thune, where she plans to open the first coffee shop the city has ever seen.
        However, her dreams of a fresh start pulling shots instead of swinging swords are hardly a sure bet. Old frenemies and Thune's shady underbelly may just upset her plans. To finally build something that will last, Viv will need some new partners and a different kind of resolve.
        A hot cup of fantasy slice-of-life with a dollop of romantic froth. `, ibsn: "9798985663211"},
        { title: "To Kill a Mockingbird", subtitle: "To Kill a Mockingbird #1", cover: "../images/tokillamockingbird.jpeg", authors: "Harper Lee", pageCount: "336", genre: "Fiction, Classics, Historical", description: `One of the most cherished stories of all time, To Kill a Mockingbird has been translated into more than forty languages, sold more than forty million copies worldwide, served as the basis for an enormously popular motion picture, and was voted one of the best novels of the twentieth century by librarians across the country. A gripping, heart-wrenching, and wholly remarkable tale of coming-of-age in a South poisoned by virulent prejudice, it views a world of great beauty and savage inequities through the eyes of a young girl, as her father--a crusading local lawyer--risks everything to defend a black man unjustly accused of a terrible crime.`, ibsn: "9780060935467"},
        { title: "Under One Roof", subtitle: "The STEMinist Novellas #1", cover: "../images/underoneroof.jpeg", authors: "Ali Hazelwood", pageCount: "112", genre: "Fiction, Romance", description: `A scientist should never cohabitate with her annoyingly hot nemesis - it leads to combustion.
        Mara, Sadie, and Hannah are friends first, scientists always. Though their fields of study might take them to different corners of the world, they can all agree on this universal truth: when it comes to love and science, opposites attract and rivals make you burn...
        As an environmental engineer, Mara knows all about the delicate nature of ecosystems. They require balance. And leaving the thermostat alone. And not stealing someone else's food. And other rules Liam, her detestable big-oil lawyer of a roommate, knows nothing about. Okay, sure, technically she's the interloper. Liam was already entrenched in his aunt's house like some glowering grumpy giant when Mara moved in, with his big muscles and kissable mouth just sitting there on the couch tempting respectable scientists to the dark side...but Helena was her mentor and Mara's not about to move out and give up her inheritance without a fight.
        The problem is, living with someone means getting to know them. And the more Mara finds out about Liam, the harder it is to loathe him...and the easier it is to love him.`, ibsn: "9780593437810"},
        { title: "The Book Thief", subtitle: "", cover: "../images/bookthief.jpeg", authors: "Markus Zusak", pageCount: "552", genre: "Fiction, Historical, Young Adult", description: `It is 1939. Nazi Germany. The country is holding its breath. Death has never been busier, and will be busier still.
        By her brother's graveside, Liesel's life is changed when she picks up a single object, partially hidden in the snow. It is The Gravedigger's Handbook, left behind there by accident, and it is her first act of book thievery. So begins a love affair with books and words, as Liesel, with the help of her accordian-playing foster father, learns to read. Soon she is stealing books from Nazi book-burnings, the mayor's wife's library, wherever there are books to be found.
        But these are dangerous times. When Liesel's foster family hides a Jew in their basement, Liesel's world is both opened up, and closed down.`, ibsn: "9780375831003"},
        { title: "Brown Girl in the Ring", subtitle: "", cover: "../images/browngirlinthering.jpeg", authors: "Nalo Hopkinson", pageCount: "256", genre: "Fiction, Fantasy, Science Fiction", description: `The rich and privileged have fled the city, barricaded it behind roadblocks, and left it to crumble. The inner city has had to rediscover old ways -- farming, barter, herb lore. But now the monied need a harvest of bodies, and so they prey upon the helpless of the streets. With nowhere to turn, a young woman must open herself to ancient truths, eternal powers, and the tragic mystery surrounding her mother and grandmother. She must bargain with gods, and give birth to new legends.`, ibsn: "9780446674331"},
        { title: "The Hobbit", subtitle: "", cover: "../images/thehobbit.jpeg", authors: "J.R.R. Tolkien", pageCount: "352 ", genre: "Fiction, Classics, Fantasy, Middle Grade", description: `Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure. They have launched a plot to raid the treasure hoard guarded by Smaug the Magnificent, a large and very dangerous dragon. Bilbo reluctantly joins their quest, unaware that on his journey to the Lonely Mountain he will encounter both a magic ring and a frightening creature known as Gollum.`, ibsn: "9780618150823"},
        { title: "You've Lost a Lot of Blood", subtitle: "", cover: "../images/lostalotofblood.jpeg", authors: "Eric LaRocca", pageCount: "209 ", genre: "Fiction, Horror, LGBTQIA+", description: `Each precious thing I show you in this book is a holy relic from the night we both perished-the night when I combed you from my hair and watered the moon with your blood.
        You've lost a lot of blood . . .`, ibsn: "9781088025758"},
        { title: "Nineteen Eighty-Four", subtitle: "", cover: "../images/1984.jpeg", authors: "George Orwell", pageCount: "368", genre: "Fiction, Classics, Dystopian", description: `Winston Smith toes the Party line, rewriting history to satisfy the demands of the Ministry of Truth. With each lie he writes, Winston grows to hate the Party that seeks power for its own sake and persecutes those who dare to commit thoughtcrimes. But as he starts to think for himself, Winston can't escape the fact that Big Brother is always watching...
        A startling and haunting vision of the world, 1984 is so powerful that it is completely convincing from start to finish. No one can deny the influence of this novel, its hold on the imaginations of multiple generations of readers, or the resiliency of its admonitions--a legacy that seems only to grow with the passage of time.`, ibsn: "9780452284234"},
        { title: "Second Chance Summer", subtitle: "", cover: "../images/secondchancesummer.jpeg", authors: "Morgan Matson", pageCount: "496", genre: "Fiction, Contemporary, Romance, Young Adult", description: `Taylor Edwards's family might not be the closest-knit--everyone is a little too busy and overscheduled--but for the most part, they get along just fine. Then, Taylor's dad gets devastating news, and her parents decide that the family will spend one last summer all together at their old lake house in the Pocono Mountains.
        Crammed into a place much smaller and more rustic than they are used to, they begin to get to know each other again. And Taylor discovers that the people she thought she had left behind haven't actually gone anywhere. Her former best friend is still around, as is her first boyfriend--and he's much cuter at seventeen than he was at twelve.
        As the summer progresses and the Edwards become more of a family, they're more aware than ever that they're battling a ticking clock. Sometimes, though, there is just enough time to get a second chance with family, with friends, and with love.`, ibsn: "9781416990680"},
        { title: "Animal Farm", subtitle: "", cover: "../images/animalfarm.jpeg", authors: "George Orwell", pageCount: "152", genre: "Fiction, Classics, Dystopian, Literary", description: `A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned--a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible.`, ibsn: "9780451526342"},
        { title: "Queer Little Nightmares", subtitle: "An Anthology of Monstrous Fiction and Poetry", cover: "../images/queerlittlenightmares.jpeg", authors: "David Ly, Daniel Zomparelli", pageCount: "272", genre: "Fiction, Poetry, LGBTQIA+", description: `The fiction and poetry of Queer Little Nightmares reimagines monsters old and new through a queer lens, subverting the horror gaze to celebrate ideas and identities canonically feared in monster lit. Throughout history, monsters have appeared in popular culture as stand-ins for the non-conforming, the marginalized of society. Pushed into the shadows as objects of fear, revulsion, and hostility, these characters have long conjured fascination and self-identification in the LGBTQ+ community, and over time, monsters have become queer icons. In Queer Little Nightmares, creatures of myth and folklore seek belonging and intimate connection, cryptids challenge their outcast status, and classic movie monsters explore the experience of coming into queerness. The characters in these stories and poems—the Minotaur camouflaged in a crowd of cosplayers, a pubescent werewolf, a Hindu revenant waiting to reunite with her lover, a tender-hearted kaiju, a lagoon creature aching for the swimmers above him, a ghost of Pride past—relish their new sparkle in the spotlight. Pushing against tropes that have historically been used to demonize, the queer creators of this collection instead ask: What does it mean to be (and to love) a monster? Contributors include Amber Dawn, David Demchuk, Hiromi Goto, jaye simpson, Eddy Boudel Tan, and Kai Cheng Thom.`, ibsn: "9781551529011"},
        { title: "The Fellowship of the Ring", subtitle: "The Lord of the Rings #1", cover: "../images/fellowshipofthering.jpeg", authors: "J.R.R. Tolkien", pageCount: "506", genre: "Fiction, Classics, Fantasy", description: `In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.`, ibsn: "9780618574940"},
        { title: "The Two Towers", subtitle: "The Lord of the Rings #2", cover: "../images/thetwotowers.jpeg", authors: "J.R.R. Tolkien", pageCount: "448", genre: "Fiction, Classics, Fantasy", description: `Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go.`, ibsn: "9780618574957"},
        { title: "The Return of the King", subtitle: "The Lord of the Rings #3", cover: "../images/returnoftheking.jpeg", authors: "J.R.R. Tolkien", pageCount: "544", genre: "Fiction, Classics, Fantasy", description: "The armies of the Dark Lord Sauron are massing as his evil shadow spreads even wider. Men, Dwarves, Elves and Ents unite forces to do battle against the Dark. Meanwhile, Frodo and Sam struggle further into Mordor, guided by the treacherous creature Gollum, in their heroic quest to destroy the One Ring…", ibsn: "9780618574971"},
        { title: "What Moves the Dead", subtitle: "", cover: "../images/whatmovesthedead.jpeg", authors: "T. Kingfisher", pageCount: "165", genre: "Fiction, Horror, LGBTQIA+", description: `When Alex Easton, a retired soldier, receives word that their childhood friend Madeline Usher is dying, they race to the ancestral home of the Ushers in the remote countryside of Ruritania.
        What they find there is a nightmare of fungal growths and possessed wildlife, surrounding a dark, pulsing lake. Madeline sleepwalks and speaks in strange voices at night, and her brother Roderick is consumed with a mysterious malady of the nerves.
        Aided by a redoubtable British mycologist and a baffled American doctor, Alex must unravel the secret of the House of Usher before it consumes them all.`, ibsn: "9781250830753" },
        { title: "The Great Gatsby", subtitle: "", cover: "../images/greatgatsby.jpeg", authors: "F. Scott Fitzgerald", pageCount: "180", genre: "Fiction, Classics, Literary", description: `This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story is of the fabulously wealthy Jay Gatsby and his new love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted "gin was the national drink and sex the national obsession," it is an exquisitely crafted tale of America in the 1920s.`, ibsn: "0743273567"},
        { title: "Tear", subtitle: "", cover: "../images/tear.png", authors: "Erica McKeen", pageCount: "304", genre: "Fiction, Horror, Literary", description: `Frances is quiet and reclusive, so much so that her upstairs roommates sometimes forget she exists. Isolated in the basement, and on the brink of graduating from university, Frances herself starts to question the realities of her own existence. She can't remember there being a lock on the door at the top of the basement stairs—and yet, when she turns the knob, the door won't open. She can't tell the difference between her childhood memories, which bloom like flowers in the dark basement, and her dreams. Worse still, she can't ignore the very real tapping sound now coming—insistently, violently—threatening to break through her bedroom wall.`, ibsn: "9781778430060"},
        { title: "The Lion, the Witch and the Wardrobe", subtitle: "The Chronicles of Narnia (Chronological Order) #2", cover: "../images/lionwitchwardrobe.jpeg", authors: "C.S. Lewis with Pauline Baynes (Illustrator)", pageCount: "208", genre: "Fiction, Childrens, Classics, Fantasy", description: `Four adventurous siblings--Peter, Susan, Edmund, and Lucy Pevensie--step through a wardrobe door and into the land of Narnia, a land frozen in eternal winter and enslaved by the power of the White Witch. But when almost all hope is lost, the return of the Great Lion, Aslan, signals a great change . . . and a great sacrifice.`, ibsn: "9780064409421"},
        { title: "The Magician's Nephew", subtitle: "The Chronicles of Narnia (Chronological Order) #1", cover: "../images/magiciansnephew.jpeg", authors: "C.S. Lewis with Pauline Baynes (Illustrator)", pageCount: "208", genre: "Fiction, Childrens, Classics, Fantasy", description: `On a daring quest to save a life, two friends are hurled into another world, where an evil sorceress seeks to enslave them. But then the lion Aslan's song weaves itself into the fabric of a new land, a land that will be known as Narnia. And in Narnia, all things are possible.`, ibsn: "9780064409438"},
        { title: "The Horse and His Boy", subtitle: "The Chronicles of Narnia (Chronological Order) #3", cover: "../images/horseandhisboy.jpeg", authors: "C.S. Lewis with Pauline Baynes (Illustrator)", pageCount: "240 ", genre: "Fiction, Childrens, Classics, Fantasy", description: `On a desperate journey, two runaways meet and join forces. Though they are only looking to escape their harsh and narrow lives, they soon find themselves at the center of a terrible battle. It is a battle that will decide their fate and the fate of Narnia itself.`, ibsn: "9780064409407"},
        { title: "Prince Caspian", subtitle: "The Chronicles of Narnia (Chronological Order) #4", cover: "../images/princecaspian.jpeg", authors: "C.S. Lewis with Pauline Baynes (Illustrator)", pageCount: "240", genre: "Fiction, Classics, Fantasy, Middle Grade", description: `The Pevensie siblings are back to help a prince denied his rightful throne as he gathers an army in a desperate attempt to rid his land of a false king. But in the end, it is a battle of honor between two men alone that will decide the fate of an entire world.`, ibsn: "9780064409445"},
        { title: "The Voyage of the Dawn Treader", subtitle: "The Chronicles of Narnia (Chronological Order) #5", cover: "../images/voyageofdawntreader.jpeg", authors: "C.S. Lewis with Pauline Baynes (Illustrator)", pageCount: "256", genre: "Fiction, Childrens, Classics, Fantasy", description: `A king and some unexpected companions embark on a voyage that will take them beyond all known lands. As they sail farther and farther from charted waters, they discover that their quest is more than they imagined and that the world's end is only the beginning.`, ibsn: "9780064409469"},
        { title: "The Silver Chair", subtitle: "The Chronicles of Narnia (Chronological Order) #6", cover: "../images/silverchair.jpeg", authors: "C.S. Lewis with Pauline Baynes (Illustrator)", pageCount: "256", genre: "Fiction, Childrens, Classics, Fantasy", description: `Through dangers untold and caverns deep and dark, a noble band of friends is sent to rescue a prince held captive. But their mission to Underland brings them face-to-face with an evil more beautiful and more deadly than they ever expected.`, ibsn: "9780064409452"},
        { title: "The Last Battle", subtitle: "The Chronicles of Narnia (Chronological Order) #7", cover: "../images/lastbattle.jpeg", authors: "C.S. Lewis with Pauline Baynes (Illustrator)", pageCount: "224", genre: "Fiction, Childrens, Classics, Fantasy", description: `During the last days of Narnia, the land faces its fiercest challenge--not an invader from without but an enemy from within. Lies and treachery have taken root, and only the king and a small band of loyal followers can prevent the destruction of all they hold dear in this, the magnificent ending to The Chronicles of Narnia.`, ibsn: "9780064409414"},
        { title: "I'm Glad My Mom Died", subtitle: "", cover: "../images/gladmymomdied.jpeg", authors: "Jennette McCurdy", pageCount: "306", genre: "Nonfiction, Memoir", description: `Jennette McCurdy was six years old when she had her first acting audition. Her mother's dream was for her only daughter to become a star, and Jennette would do anything to make her mother happy. So she went along with what Mom called “calorie restriction,” eating little and weighing herself five times a day. She endured extensive at-home makeovers while Mom chided, “Your eyelashes are invisible, okay? You think Dakota Fanning doesn't tint hers?” She was even showered by Mom until age sixteen while sharing her diaries, email, and all her income.
        In I'm Glad My Mom Died, Jennette recounts all this in unflinching detail—just as she chronicles what happens when the dream finally comes true. Cast in a new Nickelodeon series called iCarly, she is thrust into fame. Though Mom is ecstatic, emailing fan club moderators and getting on a first-name basis with the paparazzi (“Hi Gale!”), Jennette is riddled with anxiety, shame, and self-loathing, which manifest into eating disorders, addiction, and a series of unhealthy relationships. These issues only get worse when, soon after taking the lead in the iCarly spinoff Sam & Cat alongside Ariana Grande, her mother dies of cancer. Finally, after discovering therapy and quitting acting, Jennette embarks on recovery and decides for the first time in her life what she really wants.`, ibsn: "9781982185824"},
        { title: "The Diary of a Young Girl", subtitle: "", cover: "../images/annefrank.jpeg", authors: "Anne Frank with B.M. Mooyaart-Doubleday (Translator)", pageCount: "283", genre: "Nonfiction, Classics, History, Memoir", description: `Discovered in the attic in which she spent the last years of her life, Anne Frank's remarkable diary has become a world classic—a powerful reminder of the horrors of war and an eloquent testament to the human spirit.
        In 1942, with the Nazis occupying Holland, a thirteen-year-old Jewish girl and her family fled their home in Amsterdam and went into hiding. For the next two years, until their whereabouts were betrayed to the Gestapo, the Franks and another family lived cloistered in the “Secret Annexe” of an old office building. Cut off from the outside world, they faced hunger, boredom, the constant cruelties of living in confined quarters, and the ever-present threat of discovery and death. In her diary Anne Frank recorded vivid impressions of her experiences during this period. By turns thoughtful, moving, and surprisingly humorous, her account offers a fascinating commentary on human courage and frailty and a compelling self-portrait of a sensitive and spirited young woman whose promise was tragically cut short.`, ibsn: "0553296981"},
        { title: "The Honeys", subtitle: "", cover: "../images/thehoneys.jpeg", authors: "Ryan La Sala", pageCount: "336", genre: "Fiction, Horror, LGBTQIA+, Young Adult", description: `Mars has always been the lesser twin, the shadow to his sister Caroline's radiance. But when Caroline dies under horrific circumstances, Mars is propelled to learn all he can about his once-inseparable sister who'd grown tragically distant.
        Mars's genderfluidity means he's often excluded from the traditions -- and expectations -- of his politically-connected family. This includes attendance at the prestigious Aspen Conservancy Summer Academy where his sister poured so much of her time. But with his grief still fresh, he insists on attending in her place.
        What Mars finds is a bucolic fairytale not meant for him. Folksy charm and sun-drenched festivities camouflage old-fashioned gender roles and a toxic preparatory rigor. Mars seeks out his sister's old friends: a group of girls dubbed the Honeys, named for the beehives they maintain behind their cabin. They are beautiful and terrifying -- and Mars is certain they're connected to Caroline's death.
        But the longer he stays at Aspen, the more the sweet mountain breezes give way to hints of decay. Mars's memories begin to falter, bleached beneath the relentless summer sun. Something is hunting him in broad daylight, toying with his mind. If Mars can't find it soon, it will eat him alive.`, ibsn: "9781338745313"},
        { title: "Lord of the Flies", subtitle: "", cover: "../images/lordoftheflies.jpeg", authors: "William Golding", pageCount: "240", genre: "Fiction, Classics, Dystopian, Young Adult", description: `At the dawn of the next world war, a plane crashes on an uncharted island, stranding a group of schoolboys. At first, with no adult supervision, their freedom is something to celebrate; this far from civilization the boys can do anything they want. Anything. They attempt to forge their own society, failing, however, in the face of terror, sin and evil. And as order collapses, as strange howls echo in the night, as terror begins its reign, the hope of adventure seems as far from reality as the hope of being rescued. Labeled a parable, an allegory, a myth, a morality tale, a parody, a political treatise, even a vision of the apocalypse, Lord of the Flies is perhaps our most memorable tale about "the end of innocence, the darkness of man's heart."`, ibsn: "9780143124290"},
        { title: "Sometime in Summer", subtitle: "", cover: "../images/sometimeinsummer.jpeg", authors: "Katrina Leno", pageCount: "416", genre: "Fiction, Contemporary, Magical Realism, Young Adult", description: `Anna Lucia Bell believes in luck: bad luck. Bad luck made her best friend stop talking to her. Bad luck caused her parents' divorce. Bad luck is forcing her mother, Miriam, to sell the family's beloved bookstore. And it is definitely bad luck that Anna seems to be the only person in the world Miriam is unable to recommend a life-changing book.
        When Anna finds out that she and her mom are spending two months in a New England seaside town called Rockport, she expects a summer plagued with bad luck too. But Rockport has surprises in store for Anna, including a comet making its first appearance in over twenty years and two new--but familiar--friends.
        In what will prove to be the most important summer of her life so far, Anna learns about love, herself, and the magic that an ordinary summer can bring.`, ibsn: "9780316194518"},
        { title: "The Da Vinci Code", subtitle: "Robert Langdon #2", cover: "../images/davincicode.jpeg", authors: "Dan Brown", pageCount: "454", genre: "Fiction, Mystery, Thriller", description: `While in Paris on business, Harvard symbologist Robert Langdon receives an urgent late-night phone call: the elderly curator of the Louvre has been murdered inside the museum. Near the body, police have found a baffling cipher. While working to solve the enigmatic riddle, Langdon is stunned to discover it leads to a trail of clues hidden in the works of Da Vinci -- clues visible for all to see -- yet ingeniously disguised by the painter. 
        Langdon joins forces with a gifted French cryptologist, Sophie Neveu, and learns the late curator was involved in the Priory of Sion -- an actual secret society whose members included Sir Isaac Newton, Botticelli, Victor Hugo, and Da Vinci, among others. 
        In a breathless race through Paris, London, and beyond, Langdon and Neveu match wits with a faceless powerbroker who seems to anticipate their every move. Unless Langdon and Neveu can decipher the labyrinthine puzzle in time, the Priory's ancient secret -- and an explosive historical truth -- will be lost forever. `, ibsn: "9780385504201"},
        { title: "Whisper Network", subtitle: "", cover: "../images/whispernetwork.jpeg", authors: "Chandler Baker", pageCount: "352", genre: "Fiction, Mystery, Thriller", description: `Sloane, Ardie, Grace, and Rosalita have worked at Truviv, Inc. for years. The sudden death of Truviv's CEO means their boss, Ames, will likely take over the entire company. Each of the women has a different relationship with Ames, who has always been surrounded by whispers about how he treats women. Those whispers have been ignored, swept under the rug, hidden away by those in charge.
        But the world has changed, and the women are watching this promotion differently. This time, when they find out Ames is making an inappropriate move on a colleague, they aren't willing to let it go. This time, they've decided enough is enough.
        Sloane and her colleagues' decision to take a stand sets in motion a catastrophic shift in the office. Lies will be uncovered. Secrets will be exposed. And not everyone will survive. All of their lives--as women, colleagues, mothers, wives, friends, even adversaries--will change dramatically as a result.
        If only you had listened to us," they tell us on page one of Chandler Baker's Whisper Network, "none of this would have happened.`, ibsn: "9781250319470"},
        { title: "The Catcher in the Rye", subtitle: "", cover: "../images/catcherintherye.png", authors: "J.D. Salinger", pageCount: "288", genre: "Fiction, Classics, Literary", description: `The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caufield. Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days.`, ibsn: "9780316769174"},
        { title: "Jonathan Strange & Mr Norrell", subtitle: "", cover: "../images/jonathanstrange.jpeg", authors: "Susanna Clarke", pageCount: "849", genre: "Fiction, Fantasy, Historical", description: `The year is 1806. centuries have passed since practical magicians faded into the nation's past. But scholars of this glorious history discover that one remains: the reclusive Mr Norrell, whose displays of magic send a thrill through the country. Proceeding to London, he raises a beautiful woman from the dead and summons an army of ghostly ships to terrify the French. Yet the cautious, fussy Norrell is challenged by the emergence of another magician: the brilliant novice Jonathan Strange. Young, handsome and daring, Strange is the very antithesis of Norrell. So begins a dangerous battle between these two great men which overwhelms that between England and France. And their own obsessions and secret dabblings with the dark arts are going to cause more trouble than they can imagine.`, ibsn: "9781582346038"},
        { title: "The Kite Runner", subtitle: "", cover: "../images/kiterunner.jpeg", authors: "Khaled Hosseini", pageCount: "371", genre: "Fiction, Classics, Contemporary, Historical, Literary", description: `The unforgettable, heartbreaking story of the unlikely friendship between a wealthy boy and the son of his father's servant, caught in the tragic sweep of history, The Kite Runner transports readers to Afghanistan at a tense and crucial moment of change and destruction. A powerful story of friendship, it is also about the power of reading, the price of betrayal, and the possibility of redemption; and an exploration of the power of fathers over sons--their love, their sacrifices, their lies.`, ibsn: "9781594631931"},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},
        // { title: "", subtitle: "", cover: "", authors: "", pageCount: "", genre: "", description: "", ibsn: ""},

       
    ]

    // delete all the existing books
    Book.deleteMany({})
        .then(deletedBooks => {
            console.log('this is what .remove returns', deletedBooks)

            // create a bunch of new books from startBooks
            Book.create(startBooks)
                .then(data => {
                    console.log('here are the newly created books', data)
                    db.close()
                })
                .catch(error => {
                    console.log(error)
                    db.close()
                })
        })
        .catch(error => {
            console.log(error)
            // always close connection to the db
            db.close()
        })
})